version: '3.8'
services:
  server:
    build: .
    ports:
      - "4000:4000"
    depends_on: 
      - db
    restart: always
    volumes:
      - ./:/usr/src/app
    command: nodemon db.js
  db:
    image: postgres:12
    restart: always
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
      POSTGRES_USER: postgres
  redis:
    image: redis:6.0
    restart: always
    ports: 
      - "6379:6379"
